# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d4e6763d6fd21f08346ce48b980b22a192f9c96ee16480fa62813c8226359d625e9eecd733c0033d68d971ea0f2332368f8b175be83bfac27fa646627a331c6

test:
  secret_key_base: 3edad3032d1d1920e38a6cdb55389d2021f8392f75fc8dc8dc716fb207328345740a271f0031c6d940085034279470ce902a1af7f72afc3aa54e6e0ea6b58053

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
